using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


using		System.Drawing;
using		System.Windows.Forms;
using System.Xml;
using System.ComponentModel;




namespace WorldOfTheThreeKingdoms.GameForms

{
    public class formOptions : Form
    {
        private Button btnCancel;
        private Button btnOK;
        private CheckBox cbAdditionalPersonAvailable;
        private CheckBox cbCommonPersonAvailable;
        private CheckBox cbDrawMapVeil;
        private CheckBox cbDrawTroopAnimation;
        private CheckBox cbHintPopulation;
        private CheckBox cbHintPopulationUnder1000;
        private CheckBox cbIdealTendencyValid;
        private CheckBox cbMilitaryKindSpeedValid;
        private CheckBox cbMultipleResource;
        private CheckBox cbNoHintOnSmallFacility;
        private CheckBox cbPersonNaturalDeath;
        private CheckBox cbPlayBattleSound;
        private CheckBox cbPlayerPersonAvailable;
        private CheckBox cbPlayMusic;
        private CheckBox cbPlayNormalSound;
        private CheckBox cbPopulationRecruitmentLimit;
        private CheckBox cbRunWhileNotFocused;
        private CheckBox cbSingleSelectionOneClick;
        private CheckBox cbSkyEye;
        private XmlDocument commonDoc = new XmlDocument();
        private IContainer components = null;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label19;
        private Label label2;
        private Label label20;
        private Label label21;
        private Label label22;
        private Label label23;
        private Label label24;
        private Label label25;
        private Label label26;
        private Label label27;
        private Label label28;
        private Label label29;
        private Label label3;
        private Label label30;
        private Label label31;
        private Label label32;
        private Label label33;
        private Label label34;
        private Label label35;
        private Label label36;
        private Label label37;
        private Label label38;
        private Label label39;
        private Label label4;
        private Label label40;
        private Label label41;
        private Label label42;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private XmlDocument parameterDoc = new XmlDocument();
        private TabPage tabPageAIParameter;
        private TabPage tabPageEnvironment;
        private TabPage tabPageParameter;
        private TabPage tabPagePerson;
        private TextBox tbAIArchitectureDamageRate;
        private TextBox tbAIFoodRate;
        private TextBox tbAIFundRate;
        private TextBox tbAIRecruitmentSpeedRate;
        private TextBox tbAITrainingSpeedRate;
        private TextBox tbAITroopDefenceRate;
        private TextBox tbAITroopOffenceRate;
        private TextBox tbArchitectureDamageRate;
        private TextBox tbBuyFoodAgriculture;
        private TextBox tbChangeCapitalCost;
        private TextBox tbClearFieldAgricultureCostUnit;
        private TextBox tbClearFieldFundCostUnit;
        private TextBox tbConvincePersonCost;
        private TextBox tbDefaultPopulationDevelopingRate;
        private TextBox tbDestroyArchitectureCost;
        private TextBox tbFindTreasureChance;
        private TextBox tbFireDamageScale;
        private TextBox tbFollowedLeaderDefenceRateIncrement;
        private TextBox tbFollowedLeaderOffenceRateIncrement;
        private TextBox tbFoodRate;
        private TextBox tbFoodToFundDivisor;
        private TextBox tbFundRate;
        private TextBox tbFundToFoodMultiple;
        private TextBox tbGossipArchitectureCost;
        private TextBox tbHireNoFactionPersonCost;
        private TextBox tbInstigateArchitectureCost;
        private TextBox tbInternalFundCost;
        private TextBox tbInternalRate;
        private TextBox tbLearnSkillDays;
        private TextBox tbLearnStuntDays;
        private TextBox tbLearnTitleDays;
        private TextBox tbRecruitmentDomination;
        private TextBox tbRecruitmentFundCost;
        private TextBox tbRecruitmentMorale;
        private TextBox tbRecruitmentRate;
        private TextBox tbRewardPersonCost;
        private TextBox tbSellFoodCommerce;
        private TextBox tbSendSpyCost;
        private TextBox tbSurroundArchitectureDominationUnit;
        private TextBox tbTrainingRate;
        private TextBox tbTroopDamageRate;
        private TextBox tbTroopMoveSpeed;
        private TabControl tcOptions;

        public formOptions()
        {
            this.InitializeComponent();
            this.LoadCommonDoc();
            this.LoadParameterDoc();
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            this.SaveCommonDoc();
            this.SaveParameterDoc();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.tcOptions = new TabControl();
            this.tabPageEnvironment = new TabPage();
            this.cbMilitaryKindSpeedValid = new CheckBox();
            this.cbPopulationRecruitmentLimit = new CheckBox();
            this.cbHintPopulationUnder1000 = new CheckBox();
            this.cbHintPopulation = new CheckBox();
            this.label1 = new Label();
            this.tbTroopMoveSpeed = new TextBox();
            this.cbNoHintOnSmallFacility = new CheckBox();
            this.cbSingleSelectionOneClick = new CheckBox();
            this.cbMultipleResource = new CheckBox();
            this.cbSkyEye = new CheckBox();
            this.cbDrawTroopAnimation = new CheckBox();
            this.cbDrawMapVeil = new CheckBox();
            this.cbPlayBattleSound = new CheckBox();
            this.cbPlayNormalSound = new CheckBox();
            this.cbPlayMusic = new CheckBox();
            this.cbRunWhileNotFocused = new CheckBox();
            this.tabPagePerson = new TabPage();
            this.label37 = new Label();
            this.tbLearnTitleDays = new TextBox();
            this.label38 = new Label();
            this.tbLearnStuntDays = new TextBox();
            this.label39 = new Label();
            this.tbLearnSkillDays = new TextBox();
            this.label36 = new Label();
            this.tbFindTreasureChance = new TextBox();
            this.cbIdealTendencyValid = new CheckBox();
            this.cbPersonNaturalDeath = new CheckBox();
            this.cbPlayerPersonAvailable = new CheckBox();
            this.cbAdditionalPersonAvailable = new CheckBox();
            this.cbCommonPersonAvailable = new CheckBox();
            this.tabPageParameter = new TabPage();
            this.label40 = new Label();
            this.tbFireDamageScale = new TextBox();
            this.label33 = new Label();
            this.tbSurroundArchitectureDominationUnit = new TextBox();
            this.label27 = new Label();
            this.tbFoodToFundDivisor = new TextBox();
            this.label26 = new Label();
            this.tbFundToFoodMultiple = new TextBox();
            this.label25 = new Label();
            this.tbSellFoodCommerce = new TextBox();
            this.label24 = new Label();
            this.tbBuyFoodAgriculture = new TextBox();
            this.label23 = new Label();
            this.tbClearFieldAgricultureCostUnit = new TextBox();
            this.label22 = new Label();
            this.tbClearFieldFundCostUnit = new TextBox();
            this.label20 = new Label();
            this.tbGossipArchitectureCost = new TextBox();
            this.label21 = new Label();
            this.tbInstigateArchitectureCost = new TextBox();
            this.label19 = new Label();
            this.tbDestroyArchitectureCost = new TextBox();
            this.label18 = new Label();
            this.tbSendSpyCost = new TextBox();
            this.label17 = new Label();
            this.tbRewardPersonCost = new TextBox();
            this.label16 = new Label();
            this.tbConvincePersonCost = new TextBox();
            this.label15 = new Label();
            this.tbHireNoFactionPersonCost = new TextBox();
            this.label14 = new Label();
            this.tbChangeCapitalCost = new TextBox();
            this.label13 = new Label();
            this.tbRecruitmentMorale = new TextBox();
            this.label12 = new Label();
            this.tbRecruitmentDomination = new TextBox();
            this.label11 = new Label();
            this.tbRecruitmentFundCost = new TextBox();
            this.label10 = new Label();
            this.tbInternalFundCost = new TextBox();
            this.label9 = new Label();
            this.tbDefaultPopulationDevelopingRate = new TextBox();
            this.label8 = new Label();
            this.tbArchitectureDamageRate = new TextBox();
            this.label7 = new Label();
            this.tbTroopDamageRate = new TextBox();
            this.label6 = new Label();
            this.tbFoodRate = new TextBox();
            this.label5 = new Label();
            this.tbFundRate = new TextBox();
            this.label4 = new Label();
            this.tbRecruitmentRate = new TextBox();
            this.label3 = new Label();
            this.tbTrainingRate = new TextBox();
            this.label2 = new Label();
            this.tbInternalRate = new TextBox();
            this.tabPageAIParameter = new TabPage();
            this.label34 = new Label();
            this.tbAITrainingSpeedRate = new TextBox();
            this.label35 = new Label();
            this.tbAIRecruitmentSpeedRate = new TextBox();
            this.label32 = new Label();
            this.tbAITroopDefenceRate = new TextBox();
            this.label28 = new Label();
            this.tbAIArchitectureDamageRate = new TextBox();
            this.label29 = new Label();
            this.tbAITroopOffenceRate = new TextBox();
            this.label30 = new Label();
            this.tbAIFoodRate = new TextBox();
            this.label31 = new Label();
            this.tbAIFundRate = new TextBox();
            this.btnOK = new Button();
            this.btnCancel = new Button();
            this.label41 = new Label();
            this.tbFollowedLeaderOffenceRateIncrement = new TextBox();
            this.label42 = new Label();
            this.tbFollowedLeaderDefenceRateIncrement = new TextBox();
            this.tcOptions.SuspendLayout();
            this.tabPageEnvironment.SuspendLayout();
            this.tabPagePerson.SuspendLayout();
            this.tabPageParameter.SuspendLayout();
            this.tabPageAIParameter.SuspendLayout();
            base.SuspendLayout();
            this.tcOptions.Controls.Add(this.tabPageEnvironment);
            this.tcOptions.Controls.Add(this.tabPagePerson);
            this.tcOptions.Controls.Add(this.tabPageParameter);
            this.tcOptions.Controls.Add(this.tabPageAIParameter);
            this.tcOptions.Cursor = Cursors.Hand;
            this.tcOptions.Dock = DockStyle.Top;
            this.tcOptions.Location = new Point(0, 0);
            this.tcOptions.Multiline = true;
            this.tcOptions.Name = "tcOptions";
            this.tcOptions.SelectedIndex = 0;
            this.tcOptions.Size = new Size(0x1c5, 0x1a6);
            this.tcOptions.TabIndex = 0;
            this.tabPageEnvironment.Controls.Add(this.cbMilitaryKindSpeedValid);
            this.tabPageEnvironment.Controls.Add(this.cbPopulationRecruitmentLimit);
            this.tabPageEnvironment.Controls.Add(this.cbHintPopulationUnder1000);
            this.tabPageEnvironment.Controls.Add(this.cbHintPopulation);
            this.tabPageEnvironment.Controls.Add(this.label1);
            this.tabPageEnvironment.Controls.Add(this.tbTroopMoveSpeed);
            this.tabPageEnvironment.Controls.Add(this.cbNoHintOnSmallFacility);
            this.tabPageEnvironment.Controls.Add(this.cbSingleSelectionOneClick);
            this.tabPageEnvironment.Controls.Add(this.cbMultipleResource);
            this.tabPageEnvironment.Controls.Add(this.cbSkyEye);
            this.tabPageEnvironment.Controls.Add(this.cbDrawTroopAnimation);
            this.tabPageEnvironment.Controls.Add(this.cbDrawMapVeil);
            this.tabPageEnvironment.Controls.Add(this.cbPlayBattleSound);
            this.tabPageEnvironment.Controls.Add(this.cbPlayNormalSound);
            this.tabPageEnvironment.Controls.Add(this.cbPlayMusic);
            this.tabPageEnvironment.Controls.Add(this.cbRunWhileNotFocused);
            this.tabPageEnvironment.Location = new Point(4, 0x16);
            this.tabPageEnvironment.Name = "tabPageEnvironment";
            this.tabPageEnvironment.Padding = new Padding(3);
            this.tabPageEnvironment.Size = new Size(0x1bd, 0x18c);
            this.tabPageEnvironment.TabIndex = 0;
            this.tabPageEnvironment.Text = "环境";
            this.tabPageEnvironment.UseVisualStyleBackColor = true;
            this.cbMilitaryKindSpeedValid.AutoSize = true;
            this.cbMilitaryKindSpeedValid.Location = new Point(20, 0x12f);
            this.cbMilitaryKindSpeedValid.Name = "cbMilitaryKindSpeedValid";
            this.cbMilitaryKindSpeedValid.Size = new Size(0x60, 0x10);
            this.cbMilitaryKindSpeedValid.TabIndex = 15;
            this.cbMilitaryKindSpeedValid.Text = "部队速率有效";
            this.cbMilitaryKindSpeedValid.UseVisualStyleBackColor = true;
            this.cbPopulationRecruitmentLimit.AutoSize = true;
            this.cbPopulationRecruitmentLimit.Location = new Point(20, 0x119);
            this.cbPopulationRecruitmentLimit.Name = "cbPopulationRecruitmentLimit";
            this.cbPopulationRecruitmentLimit.Size = new Size(0x9c, 0x10);
            this.cbPopulationRecruitmentLimit.TabIndex = 14;
            this.cbPopulationRecruitmentLimit.Text = "人口小于兵力时禁止征兵";
            this.cbPopulationRecruitmentLimit.UseVisualStyleBackColor = true;
            this.cbHintPopulationUnder1000.AutoSize = true;
            this.cbHintPopulationUnder1000.Location = new Point(20, 0x103);
            this.cbHintPopulationUnder1000.Name = "cbHintPopulationUnder1000";
            this.cbHintPopulationUnder1000.Size = new Size(0xa8, 0x10);
            this.cbHintPopulationUnder1000.TabIndex = 13;
            this.cbHintPopulationUnder1000.Text = "提示1000人以下的人口迁移";
            this.cbHintPopulationUnder1000.UseVisualStyleBackColor = true;
            this.cbHintPopulation.AutoSize = true;
            this.cbHintPopulation.Location = new Point(20, 0xed);
            this.cbHintPopulation.Name = "cbHintPopulation";
            this.cbHintPopulation.Size = new Size(0x6c, 0x10);
            this.cbHintPopulation.TabIndex = 12;
            this.cbHintPopulation.Text = "提示人口的迁移";
            this.cbHintPopulation.UseVisualStyleBackColor = true;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0x12, 330);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0xb9, 12);
            this.label1.TabIndex = 11;
            this.label1.Text = "部队移动速度（数字越大则越慢）";
            this.tbTroopMoveSpeed.Location = new Point(0xd1, 0x147);
            this.tbTroopMoveSpeed.MaxLength = 1;
            this.tbTroopMoveSpeed.Name = "tbTroopMoveSpeed";
            this.tbTroopMoveSpeed.RightToLeft = RightToLeft.Yes;
            this.tbTroopMoveSpeed.Size = new Size(0x1b, 0x15);
            this.tbTroopMoveSpeed.TabIndex = 10;
            this.tbTroopMoveSpeed.Text = "0";
            this.cbNoHintOnSmallFacility.AutoSize = true;
            this.cbNoHintOnSmallFacility.Location = new Point(20, 0xd7);
            this.cbNoHintOnSmallFacility.Name = "cbNoHintOnSmallFacility";
            this.cbNoHintOnSmallFacility.Size = new Size(0xa8, 0x10);
            this.cbNoHintOnSmallFacility.TabIndex = 9;
            this.cbNoHintOnSmallFacility.Text = "不提示小型设施的建设完成";
            this.cbNoHintOnSmallFacility.UseVisualStyleBackColor = true;
            this.cbSingleSelectionOneClick.AutoSize = true;
            this.cbSingleSelectionOneClick.Location = new Point(20, 0xc1);
            this.cbSingleSelectionOneClick.Name = "cbSingleSelectionOneClick";
            this.cbSingleSelectionOneClick.Size = new Size(0xd8, 0x10);
            this.cbSingleSelectionOneClick.TabIndex = 8;
            this.cbSingleSelectionOneClick.Text = "从某列表中选择单一项时单击即确定";
            this.cbSingleSelectionOneClick.UseVisualStyleBackColor = true;
            this.cbMultipleResource.AutoSize = true;
            this.cbMultipleResource.Location = new Point(20, 0xab);
            this.cbMultipleResource.Name = "cbMultipleResource";
            this.cbMultipleResource.Size = new Size(0x60, 0x10);
            this.cbMultipleResource.TabIndex = 7;
            this.cbMultipleResource.Text = "资源收入加倍";
            this.cbMultipleResource.UseVisualStyleBackColor = true;
            this.cbSkyEye.AutoSize = true;
            this.cbSkyEye.Location = new Point(20, 0x95);
            this.cbSkyEye.Name = "cbSkyEye";
            this.cbSkyEye.Size = new Size(0x60, 0x10);
            this.cbSkyEye.TabIndex = 6;
            this.cbSkyEye.Text = "默认开启天眼";
            this.cbSkyEye.UseVisualStyleBackColor = true;
            this.cbDrawTroopAnimation.AutoSize = true;
            this.cbDrawTroopAnimation.Location = new Point(20, 0x7f);
            this.cbDrawTroopAnimation.Name = "cbDrawTroopAnimation";
            this.cbDrawTroopAnimation.Size = new Size(0x60, 0x10);
            this.cbDrawTroopAnimation.TabIndex = 5;
            this.cbDrawTroopAnimation.Text = "显示部队动画";
            this.cbDrawTroopAnimation.UseVisualStyleBackColor = true;
            this.cbDrawMapVeil.AutoSize = true;
            this.cbDrawMapVeil.Location = new Point(20, 0x69);
            this.cbDrawMapVeil.Name = "cbDrawMapVeil";
            this.cbDrawMapVeil.Size = new Size(0x60, 0x10);
            this.cbDrawMapVeil.TabIndex = 4;
            this.cbDrawMapVeil.Text = "显示地图烟幕";
            this.cbDrawMapVeil.UseVisualStyleBackColor = true;
            this.cbPlayBattleSound.AutoSize = true;
            this.cbPlayBattleSound.Location = new Point(20, 0x53);
            this.cbPlayBattleSound.Name = "cbPlayBattleSound";
            this.cbPlayBattleSound.Size = new Size(0x60, 0x10);
            this.cbPlayBattleSound.TabIndex = 3;
            this.cbPlayBattleSound.Text = "播放战斗音效";
            this.cbPlayBattleSound.UseVisualStyleBackColor = true;
            this.cbPlayNormalSound.AutoSize = true;
            this.cbPlayNormalSound.Location = new Point(20, 0x3d);
            this.cbPlayNormalSound.Name = "cbPlayNormalSound";
            this.cbPlayNormalSound.Size = new Size(0x60, 0x10);
            this.cbPlayNormalSound.TabIndex = 2;
            this.cbPlayNormalSound.Text = "播放一般音效";
            this.cbPlayNormalSound.UseVisualStyleBackColor = true;
            this.cbPlayMusic.AutoSize = true;
            this.cbPlayMusic.Location = new Point(20, 0x27);
            this.cbPlayMusic.Name = "cbPlayMusic";
            this.cbPlayMusic.Size = new Size(0x48, 0x10);
            this.cbPlayMusic.TabIndex = 1;
            this.cbPlayMusic.Text = "播放音乐";
            this.cbPlayMusic.UseVisualStyleBackColor = true;
            this.cbRunWhileNotFocused.AutoSize = true;
            this.cbRunWhileNotFocused.Location = new Point(20, 0x11);
            this.cbRunWhileNotFocused.Name = "cbRunWhileNotFocused";
            this.cbRunWhileNotFocused.Size = new Size(180, 0x10);
            this.cbRunWhileNotFocused.TabIndex = 0;
            this.cbRunWhileNotFocused.Text = "游戏窗体失去焦点时继续运行";
            this.cbRunWhileNotFocused.UseVisualStyleBackColor = true;
            this.tabPagePerson.Controls.Add(this.label42);
            this.tabPagePerson.Controls.Add(this.tbFollowedLeaderDefenceRateIncrement);
            this.tabPagePerson.Controls.Add(this.label41);
            this.tabPagePerson.Controls.Add(this.tbFollowedLeaderOffenceRateIncrement);
            this.tabPagePerson.Controls.Add(this.label37);
            this.tabPagePerson.Controls.Add(this.tbLearnTitleDays);
            this.tabPagePerson.Controls.Add(this.label38);
            this.tabPagePerson.Controls.Add(this.tbLearnStuntDays);
            this.tabPagePerson.Controls.Add(this.label39);
            this.tabPagePerson.Controls.Add(this.tbLearnSkillDays);
            this.tabPagePerson.Controls.Add(this.label36);
            this.tabPagePerson.Controls.Add(this.tbFindTreasureChance);
            this.tabPagePerson.Controls.Add(this.cbIdealTendencyValid);
            this.tabPagePerson.Controls.Add(this.cbPersonNaturalDeath);
            this.tabPagePerson.Controls.Add(this.cbPlayerPersonAvailable);
            this.tabPagePerson.Controls.Add(this.cbAdditionalPersonAvailable);
            this.tabPagePerson.Controls.Add(this.cbCommonPersonAvailable);
            this.tabPagePerson.Location = new Point(4, 0x16);
            this.tabPagePerson.Name = "tabPagePerson";
            this.tabPagePerson.Padding = new Padding(3);
            this.tabPagePerson.Size = new Size(0x1bd, 0x18c);
            this.tabPagePerson.TabIndex = 1;
            this.tabPagePerson.Text = "人物";
            this.tabPagePerson.UseVisualStyleBackColor = true;
            this.label37.AutoSize = true;
            this.label37.Location = new Point(0x13, 0xd8);
            this.label37.Name = "label37";
            this.label37.Size = new Size(0x4d, 12);
            this.label37.TabIndex = 0x13;
            this.label37.Text = "修习称号时间";
            this.tbLearnTitleDays.Location = new Point(0x71, 0xd5);
            this.tbLearnTitleDays.Name = "tbLearnTitleDays";
            this.tbLearnTitleDays.Size = new Size(0x47, 0x15);
            this.tbLearnTitleDays.TabIndex = 0x12;
            this.label38.AutoSize = true;
            this.label38.Location = new Point(0x13, 0xbd);
            this.label38.Name = "label38";
            this.label38.Size = new Size(0x4d, 12);
            this.label38.TabIndex = 0x11;
            this.label38.Text = "修习特技时间";
            this.tbLearnStuntDays.Location = new Point(0x71, 0xba);
            this.tbLearnStuntDays.Name = "tbLearnStuntDays";
            this.tbLearnStuntDays.Size = new Size(0x47, 0x15);
            this.tbLearnStuntDays.TabIndex = 0x10;
            this.label39.AutoSize = true;
            this.label39.Location = new Point(0x13, 0xa2);
            this.label39.Name = "label39";
            this.label39.Size = new Size(0x4d, 12);
            this.label39.TabIndex = 15;
            this.label39.Text = "修习技能时间";
            this.tbLearnSkillDays.Location = new Point(0x71, 0x9f);
            this.tbLearnSkillDays.Name = "tbLearnSkillDays";
            this.tbLearnSkillDays.Size = new Size(0x47, 0x15);
            this.tbLearnSkillDays.TabIndex = 14;
            this.label36.AutoSize = true;
            this.label36.Location = new Point(0x11, 0x84);
            this.label36.Name = "label36";
            this.label36.Size = new Size(0xd1, 12);
            this.label36.TabIndex = 13;
            this.label36.Text = "宝物发现概率（数字越大越容易发现）";
            this.tbFindTreasureChance.Location = new Point(0xe8, 0x81);
            this.tbFindTreasureChance.MaxLength = 2;
            this.tbFindTreasureChance.Name = "tbFindTreasureChance";
            this.tbFindTreasureChance.RightToLeft = RightToLeft.Yes;
            this.tbFindTreasureChance.Size = new Size(0x19, 0x15);
            this.tbFindTreasureChance.TabIndex = 12;
            this.tbFindTreasureChance.Text = "10";
            this.cbIdealTendencyValid.AutoSize = true;
            this.cbIdealTendencyValid.Location = new Point(0x13, 0x6a);
            this.cbIdealTendencyValid.Name = "cbIdealTendencyValid";
            this.cbIdealTendencyValid.Size = new Size(120, 0x10);
            this.cbIdealTendencyValid.TabIndex = 4;
            this.cbIdealTendencyValid.Text = "出仕相性考虑有效";
            this.cbIdealTendencyValid.UseVisualStyleBackColor = true;
            this.cbPersonNaturalDeath.AutoSize = true;
            this.cbPersonNaturalDeath.Location = new Point(0x13, 0x54);
            this.cbPersonNaturalDeath.Name = "cbPersonNaturalDeath";
            this.cbPersonNaturalDeath.Size = new Size(0x60, 0x10);
            this.cbPersonNaturalDeath.TabIndex = 3;
            this.cbPersonNaturalDeath.Text = "人物自然死亡";
            this.cbPersonNaturalDeath.UseVisualStyleBackColor = true;
            this.cbPlayerPersonAvailable.AutoSize = true;
            this.cbPlayerPersonAvailable.Location = new Point(0x13, 0x3e);
            this.cbPlayerPersonAvailable.Name = "cbPlayerPersonAvailable";
            this.cbPlayerPersonAvailable.Size = new Size(0xae, 0x10);
            this.cbPlayerPersonAvailable.TabIndex = 2;
            this.cbPlayerPersonAvailable.Text = "玩家人物登场（9000-9999）";
            this.cbPlayerPersonAvailable.UseVisualStyleBackColor = true;
            this.cbAdditionalPersonAvailable.AutoSize = true;
            this.cbAdditionalPersonAvailable.Location = new Point(0x13, 40);
            this.cbAdditionalPersonAvailable.Name = "cbAdditionalPersonAvailable";
            this.cbAdditionalPersonAvailable.Size = new Size(0xae, 0x10);
            this.cbAdditionalPersonAvailable.TabIndex = 1;
            this.cbAdditionalPersonAvailable.Text = "附加人物登场（8000-8999）";
            this.cbAdditionalPersonAvailable.UseVisualStyleBackColor = true;
            this.cbCommonPersonAvailable.AutoSize = true;
            this.cbCommonPersonAvailable.Location = new Point(0x13, 0x12);
            this.cbCommonPersonAvailable.Name = "cbCommonPersonAvailable";
            this.cbCommonPersonAvailable.Size = new Size(0xae, 0x10);
            this.cbCommonPersonAvailable.TabIndex = 0;
            this.cbCommonPersonAvailable.Text = "一般人物登场（0000-6999）";
            this.cbCommonPersonAvailable.UseVisualStyleBackColor = true;
            this.tabPageParameter.Controls.Add(this.label40);
            this.tabPageParameter.Controls.Add(this.tbFireDamageScale);
            this.tabPageParameter.Controls.Add(this.label33);
            this.tabPageParameter.Controls.Add(this.tbSurroundArchitectureDominationUnit);
            this.tabPageParameter.Controls.Add(this.label27);
            this.tabPageParameter.Controls.Add(this.tbFoodToFundDivisor);
            this.tabPageParameter.Controls.Add(this.label26);
            this.tabPageParameter.Controls.Add(this.tbFundToFoodMultiple);
            this.tabPageParameter.Controls.Add(this.label25);
            this.tabPageParameter.Controls.Add(this.tbSellFoodCommerce);
            this.tabPageParameter.Controls.Add(this.label24);
            this.tabPageParameter.Controls.Add(this.tbBuyFoodAgriculture);
            this.tabPageParameter.Controls.Add(this.label23);
            this.tabPageParameter.Controls.Add(this.tbClearFieldAgricultureCostUnit);
            this.tabPageParameter.Controls.Add(this.label22);
            this.tabPageParameter.Controls.Add(this.tbClearFieldFundCostUnit);
            this.tabPageParameter.Controls.Add(this.label20);
            this.tabPageParameter.Controls.Add(this.tbGossipArchitectureCost);
            this.tabPageParameter.Controls.Add(this.label21);
            this.tabPageParameter.Controls.Add(this.tbInstigateArchitectureCost);
            this.tabPageParameter.Controls.Add(this.label19);
            this.tabPageParameter.Controls.Add(this.tbDestroyArchitectureCost);
            this.tabPageParameter.Controls.Add(this.label18);
            this.tabPageParameter.Controls.Add(this.tbSendSpyCost);
            this.tabPageParameter.Controls.Add(this.label17);
            this.tabPageParameter.Controls.Add(this.tbRewardPersonCost);
            this.tabPageParameter.Controls.Add(this.label16);
            this.tabPageParameter.Controls.Add(this.tbConvincePersonCost);
            this.tabPageParameter.Controls.Add(this.label15);
            this.tabPageParameter.Controls.Add(this.tbHireNoFactionPersonCost);
            this.tabPageParameter.Controls.Add(this.label14);
            this.tabPageParameter.Controls.Add(this.tbChangeCapitalCost);
            this.tabPageParameter.Controls.Add(this.label13);
            this.tabPageParameter.Controls.Add(this.tbRecruitmentMorale);
            this.tabPageParameter.Controls.Add(this.label12);
            this.tabPageParameter.Controls.Add(this.tbRecruitmentDomination);
            this.tabPageParameter.Controls.Add(this.label11);
            this.tabPageParameter.Controls.Add(this.tbRecruitmentFundCost);
            this.tabPageParameter.Controls.Add(this.label10);
            this.tabPageParameter.Controls.Add(this.tbInternalFundCost);
            this.tabPageParameter.Controls.Add(this.label9);
            this.tabPageParameter.Controls.Add(this.tbDefaultPopulationDevelopingRate);
            this.tabPageParameter.Controls.Add(this.label8);
            this.tabPageParameter.Controls.Add(this.tbArchitectureDamageRate);
            this.tabPageParameter.Controls.Add(this.label7);
            this.tabPageParameter.Controls.Add(this.tbTroopDamageRate);
            this.tabPageParameter.Controls.Add(this.label6);
            this.tabPageParameter.Controls.Add(this.tbFoodRate);
            this.tabPageParameter.Controls.Add(this.label5);
            this.tabPageParameter.Controls.Add(this.tbFundRate);
            this.tabPageParameter.Controls.Add(this.label4);
            this.tabPageParameter.Controls.Add(this.tbRecruitmentRate);
            this.tabPageParameter.Controls.Add(this.label3);
            this.tabPageParameter.Controls.Add(this.tbTrainingRate);
            this.tabPageParameter.Controls.Add(this.label2);
            this.tabPageParameter.Controls.Add(this.tbInternalRate);
            this.tabPageParameter.Location = new Point(4, 0x16);
            this.tabPageParameter.Name = "tabPageParameter";
            this.tabPageParameter.Padding = new Padding(3);
            this.tabPageParameter.Size = new Size(0x1bd, 0x18c);
            this.tabPageParameter.TabIndex = 2;
            this.tabPageParameter.Text = "参数";
            this.tabPageParameter.UseVisualStyleBackColor = true;
            this.label40.AutoSize = true;
            this.label40.Location = new Point(8, 0xfc);
            this.label40.Name = "label40";
            this.label40.Size = new Size(0x41, 12);
            this.label40.TabIndex = 0x37;
            this.label40.Text = "火焰伤害率";
            this.tbFireDamageScale.Location = new Point(0x66, 0xf9);
            this.tbFireDamageScale.Name = "tbFireDamageScale";
            this.tbFireDamageScale.Size = new Size(0x47, 0x15);
            this.tbFireDamageScale.TabIndex = 0x36;
            this.label33.AutoSize = true;
            this.label33.Location = new Point(8, 0xe1);
            this.label33.Name = "label33";
            this.label33.Size = new Size(0x4d, 12);
            this.label33.TabIndex = 0x35;
            this.label33.Text = "围城统治单位";
            this.tbSurroundArchitectureDominationUnit.Location = new Point(0x66, 0xde);
            this.tbSurroundArchitectureDominationUnit.Name = "tbSurroundArchitectureDominationUnit";
            this.tbSurroundArchitectureDominationUnit.Size = new Size(0x47, 0x15);
            this.tbSurroundArchitectureDominationUnit.TabIndex = 0x34;
            this.label27.AutoSize = true;
            this.label27.Location = new Point(8, 360);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x59, 12);
            this.label27.TabIndex = 0x33;
            this.label27.Text = "粮草换资金除数";
            this.tbFoodToFundDivisor.Location = new Point(0x66, 0x165);
            this.tbFoodToFundDivisor.Name = "tbFoodToFundDivisor";
            this.tbFoodToFundDivisor.Size = new Size(0x47, 0x15);
            this.tbFoodToFundDivisor.TabIndex = 50;
            this.label26.AutoSize = true;
            this.label26.Location = new Point(8, 0x14d);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x59, 12);
            this.label26.TabIndex = 0x31;
            this.label26.Text = "资金换粮草乘数";
            this.tbFundToFoodMultiple.Location = new Point(0x66, 330);
            this.tbFundToFoodMultiple.Name = "tbFundToFoodMultiple";
            this.tbFundToFoodMultiple.Size = new Size(0x47, 0x15);
            this.tbFundToFoodMultiple.TabIndex = 0x30;
            this.label25.AutoSize = true;
            this.label25.Location = new Point(8, 0x132);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x4d, 12);
            this.label25.TabIndex = 0x2f;
            this.label25.Text = "卖粮所需商业";
            this.tbSellFoodCommerce.Location = new Point(0x66, 0x12f);
            this.tbSellFoodCommerce.Name = "tbSellFoodCommerce";
            this.tbSellFoodCommerce.Size = new Size(0x47, 0x15);
            this.tbSellFoodCommerce.TabIndex = 0x2e;
            this.label24.AutoSize = true;
            this.label24.Location = new Point(8, 0x117);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x4d, 12);
            this.label24.TabIndex = 0x2d;
            this.label24.Text = "买粮所需农业";
            this.tbBuyFoodAgriculture.Location = new Point(0x66, 0x114);
            this.tbBuyFoodAgriculture.Name = "tbBuyFoodAgriculture";
            this.tbBuyFoodAgriculture.Size = new Size(0x47, 0x15);
            this.tbBuyFoodAgriculture.TabIndex = 0x2c;
            this.label23.AutoSize = true;
            this.label23.Location = new Point(0xfe, 360);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x4d, 12);
            this.label23.TabIndex = 0x2b;
            this.label23.Text = "清野农业单位";
            this.tbClearFieldAgricultureCostUnit.Location = new Point(0x15c, 0x165);
            this.tbClearFieldAgricultureCostUnit.Name = "tbClearFieldAgricultureCostUnit";
            this.tbClearFieldAgricultureCostUnit.Size = new Size(0x47, 0x15);
            this.tbClearFieldAgricultureCostUnit.TabIndex = 0x2a;
            this.label22.AutoSize = true;
            this.label22.Location = new Point(0xfe, 0x14d);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x4d, 12);
            this.label22.TabIndex = 0x29;
            this.label22.Text = "清野资金单位";
            this.tbClearFieldFundCostUnit.Location = new Point(0x15c, 330);
            this.tbClearFieldFundCostUnit.Name = "tbClearFieldFundCostUnit";
            this.tbClearFieldFundCostUnit.Size = new Size(0x47, 0x15);
            this.tbClearFieldFundCostUnit.TabIndex = 40;
            this.label20.AutoSize = true;
            this.label20.Location = new Point(0xfe, 0x132);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x4d, 12);
            this.label20.TabIndex = 0x27;
            this.label20.Text = "流言所需资金";
            this.tbGossipArchitectureCost.Location = new Point(0x15c, 0x12f);
            this.tbGossipArchitectureCost.Name = "tbGossipArchitectureCost";
            this.tbGossipArchitectureCost.Size = new Size(0x47, 0x15);
            this.tbGossipArchitectureCost.TabIndex = 0x26;
            this.label21.AutoSize = true;
            this.label21.Location = new Point(0xfe, 0x117);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x4d, 12);
            this.label21.TabIndex = 0x25;
            this.label21.Text = "煽动所需资金";
            this.tbInstigateArchitectureCost.Location = new Point(0x15c, 0x114);
            this.tbInstigateArchitectureCost.Name = "tbInstigateArchitectureCost";
            this.tbInstigateArchitectureCost.Size = new Size(0x47, 0x15);
            this.tbInstigateArchitectureCost.TabIndex = 0x24;
            this.label19.AutoSize = true;
            this.label19.Location = new Point(0xfe, 0xfc);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x4d, 12);
            this.label19.TabIndex = 0x23;
            this.label19.Text = "破坏所需资金";
            this.tbDestroyArchitectureCost.Location = new Point(0x15c, 0xf9);
            this.tbDestroyArchitectureCost.Name = "tbDestroyArchitectureCost";
            this.tbDestroyArchitectureCost.Size = new Size(0x47, 0x15);
            this.tbDestroyArchitectureCost.TabIndex = 0x22;
            this.label18.AutoSize = true;
            this.label18.Location = new Point(0xfe, 0xe1);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x4d, 12);
            this.label18.TabIndex = 0x21;
            this.label18.Text = "间谍所需资金";
            this.tbSendSpyCost.Location = new Point(0x15c, 0xde);
            this.tbSendSpyCost.Name = "tbSendSpyCost";
            this.tbSendSpyCost.Size = new Size(0x47, 0x15);
            this.tbSendSpyCost.TabIndex = 0x20;
            this.label17.AutoSize = true;
            this.label17.Location = new Point(0xfe, 0xc6);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x4d, 12);
            this.label17.TabIndex = 0x1f;
            this.label17.Text = "褒奖所需资金";
            this.tbRewardPersonCost.Location = new Point(0x15c, 0xc3);
            this.tbRewardPersonCost.Name = "tbRewardPersonCost";
            this.tbRewardPersonCost.Size = new Size(0x47, 0x15);
            this.tbRewardPersonCost.TabIndex = 30;
            this.label16.AutoSize = true;
            this.label16.Location = new Point(0xfe, 0xab);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x4d, 12);
            this.label16.TabIndex = 0x1d;
            this.label16.Text = "说服所需资金";
            this.tbConvincePersonCost.Location = new Point(0x15c, 0xa8);
            this.tbConvincePersonCost.Name = "tbConvincePersonCost";
            this.tbConvincePersonCost.Size = new Size(0x47, 0x15);
            this.tbConvincePersonCost.TabIndex = 0x1c;
            this.label15.AutoSize = true;
            this.label15.Location = new Point(0xfe, 0x90);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x4d, 12);
            this.label15.TabIndex = 0x1b;
            this.label15.Text = "录用资金单位";
            this.tbHireNoFactionPersonCost.Location = new Point(0x15c, 0x8d);
            this.tbHireNoFactionPersonCost.Name = "tbHireNoFactionPersonCost";
            this.tbHireNoFactionPersonCost.Size = new Size(0x47, 0x15);
            this.tbHireNoFactionPersonCost.TabIndex = 0x1a;
            this.label14.AutoSize = true;
            this.label14.Location = new Point(0xfe, 0x75);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x4d, 12);
            this.label14.TabIndex = 0x19;
            this.label14.Text = "迁都资金单位";
            this.tbChangeCapitalCost.Location = new Point(0x15c, 0x72);
            this.tbChangeCapitalCost.Name = "tbChangeCapitalCost";
            this.tbChangeCapitalCost.Size = new Size(0x47, 0x15);
            this.tbChangeCapitalCost.TabIndex = 0x18;
            this.label13.AutoSize = true;
            this.label13.Location = new Point(0xfe, 90);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x4d, 12);
            this.label13.TabIndex = 0x17;
            this.label13.Text = "补充最小民心";
            this.tbRecruitmentMorale.Location = new Point(0x15c, 0x57);
            this.tbRecruitmentMorale.Name = "tbRecruitmentMorale";
            this.tbRecruitmentMorale.Size = new Size(0x47, 0x15);
            this.tbRecruitmentMorale.TabIndex = 0x16;
            this.label12.AutoSize = true;
            this.label12.Location = new Point(0xfe, 0x3f);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x4d, 12);
            this.label12.TabIndex = 0x15;
            this.label12.Text = "补充最小统治";
            this.tbRecruitmentDomination.Location = new Point(0x15c, 60);
            this.tbRecruitmentDomination.Name = "tbRecruitmentDomination";
            this.tbRecruitmentDomination.Size = new Size(0x47, 0x15);
            this.tbRecruitmentDomination.TabIndex = 20;
            this.label11.AutoSize = true;
            this.label11.Location = new Point(0xfe, 0x24);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x4d, 12);
            this.label11.TabIndex = 0x13;
            this.label11.Text = "补充资金单位";
            this.tbRecruitmentFundCost.Location = new Point(0x15c, 0x21);
            this.tbRecruitmentFundCost.Name = "tbRecruitmentFundCost";
            this.tbRecruitmentFundCost.Size = new Size(0x47, 0x15);
            this.tbRecruitmentFundCost.TabIndex = 0x12;
            this.label10.AutoSize = true;
            this.label10.Location = new Point(0xfe, 9);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x4d, 12);
            this.label10.TabIndex = 0x11;
            this.label10.Text = "内政资金单位";
            this.tbInternalFundCost.Location = new Point(0x15c, 6);
            this.tbInternalFundCost.Name = "tbInternalFundCost";
            this.tbInternalFundCost.Size = new Size(0x47, 0x15);
            this.tbInternalFundCost.TabIndex = 0x10;
            this.label9.AutoSize = true;
            this.label9.Location = new Point(8, 0xc6);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x59, 12);
            this.label9.TabIndex = 15;
            this.label9.Text = "人口默认增长率";
            this.tbDefaultPopulationDevelopingRate.Location = new Point(0x66, 0xc3);
            this.tbDefaultPopulationDevelopingRate.Name = "tbDefaultPopulationDevelopingRate";
            this.tbDefaultPopulationDevelopingRate.Size = new Size(0x47, 0x15);
            this.tbDefaultPopulationDevelopingRate.TabIndex = 14;
            this.label8.AutoSize = true;
            this.label8.Location = new Point(8, 0xab);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x41, 12);
            this.label8.TabIndex = 13;
            this.label8.Text = "建筑伤害率";
            this.tbArchitectureDamageRate.Location = new Point(0x66, 0xa8);
            this.tbArchitectureDamageRate.Name = "tbArchitectureDamageRate";
            this.tbArchitectureDamageRate.Size = new Size(0x47, 0x15);
            this.tbArchitectureDamageRate.TabIndex = 12;
            this.label7.AutoSize = true;
            this.label7.Location = new Point(8, 0x90);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x41, 12);
            this.label7.TabIndex = 11;
            this.label7.Text = "部队伤害率";
            this.tbTroopDamageRate.Location = new Point(0x66, 0x8d);
            this.tbTroopDamageRate.Name = "tbTroopDamageRate";
            this.tbTroopDamageRate.Size = new Size(0x47, 0x15);
            this.tbTroopDamageRate.TabIndex = 10;
            this.label6.AutoSize = true;
            this.label6.Location = new Point(8, 0x75);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x41, 12);
            this.label6.TabIndex = 9;
            this.label6.Text = "粮草收入率";
            this.tbFoodRate.Location = new Point(0x66, 0x72);
            this.tbFoodRate.Name = "tbFoodRate";
            this.tbFoodRate.Size = new Size(0x47, 0x15);
            this.tbFoodRate.TabIndex = 8;
            this.label5.AutoSize = true;
            this.label5.Location = new Point(8, 90);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x41, 12);
            this.label5.TabIndex = 7;
            this.label5.Text = "资金收入率";
            this.tbFundRate.Location = new Point(0x66, 0x57);
            this.tbFundRate.Name = "tbFundRate";
            this.tbFundRate.Size = new Size(0x47, 0x15);
            this.tbFundRate.TabIndex = 6;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(8, 0x3f);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x35, 12);
            this.label4.TabIndex = 5;
            this.label4.Text = "补充速率";
            this.tbRecruitmentRate.Location = new Point(0x66, 60);
            this.tbRecruitmentRate.Name = "tbRecruitmentRate";
            this.tbRecruitmentRate.Size = new Size(0x47, 0x15);
            this.tbRecruitmentRate.TabIndex = 4;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(8, 0x24);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x35, 12);
            this.label3.TabIndex = 3;
            this.label3.Text = "训练速率";
            this.tbTrainingRate.Location = new Point(0x66, 0x21);
            this.tbTrainingRate.Name = "tbTrainingRate";
            this.tbTrainingRate.Size = new Size(0x47, 0x15);
            this.tbTrainingRate.TabIndex = 2;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(8, 9);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x35, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "内政速率";
            this.tbInternalRate.Location = new Point(0x66, 6);
            this.tbInternalRate.Name = "tbInternalRate";
            this.tbInternalRate.Size = new Size(0x47, 0x15);
            this.tbInternalRate.TabIndex = 0;
            this.tabPageAIParameter.Controls.Add(this.label34);
            this.tabPageAIParameter.Controls.Add(this.tbAITrainingSpeedRate);
            this.tabPageAIParameter.Controls.Add(this.label35);
            this.tabPageAIParameter.Controls.Add(this.tbAIRecruitmentSpeedRate);
            this.tabPageAIParameter.Controls.Add(this.label32);
            this.tabPageAIParameter.Controls.Add(this.tbAITroopDefenceRate);
            this.tabPageAIParameter.Controls.Add(this.label28);
            this.tabPageAIParameter.Controls.Add(this.tbAIArchitectureDamageRate);
            this.tabPageAIParameter.Controls.Add(this.label29);
            this.tabPageAIParameter.Controls.Add(this.tbAITroopOffenceRate);
            this.tabPageAIParameter.Controls.Add(this.label30);
            this.tabPageAIParameter.Controls.Add(this.tbAIFoodRate);
            this.tabPageAIParameter.Controls.Add(this.label31);
            this.tabPageAIParameter.Controls.Add(this.tbAIFundRate);
            this.tabPageAIParameter.Location = new Point(4, 0x16);
            this.tabPageAIParameter.Name = "tabPageAIParameter";
            this.tabPageAIParameter.Padding = new Padding(3);
            this.tabPageAIParameter.Size = new Size(0x1bd, 0x18c);
            this.tabPageAIParameter.TabIndex = 3;
            this.tabPageAIParameter.Text = "电脑";
            this.tabPageAIParameter.UseVisualStyleBackColor = true;
            this.label34.AutoSize = true;
            this.label34.Location = new Point(8, 0x9a);
            this.label34.Name = "label34";
            this.label34.Size = new Size(0x4d, 12);
            this.label34.TabIndex = 0x1b;
            this.label34.Text = "电脑训练速度";
            this.tbAITrainingSpeedRate.Location = new Point(0x84, 0x97);
            this.tbAITrainingSpeedRate.Name = "tbAITrainingSpeedRate";
            this.tbAITrainingSpeedRate.Size = new Size(0x47, 0x15);
            this.tbAITrainingSpeedRate.TabIndex = 0x1a;
            this.label35.AutoSize = true;
            this.label35.Location = new Point(8, 0xb5);
            this.label35.Name = "label35";
            this.label35.Size = new Size(0x4d, 12);
            this.label35.TabIndex = 0x19;
            this.label35.Text = "电脑征兵速度";
            this.tbAIRecruitmentSpeedRate.Location = new Point(0x84, 0xb2);
            this.tbAIRecruitmentSpeedRate.Name = "tbAIRecruitmentSpeedRate";
            this.tbAIRecruitmentSpeedRate.Size = new Size(0x47, 0x15);
            this.tbAIRecruitmentSpeedRate.TabIndex = 0x18;
            this.label32.AutoSize = true;
            this.label32.Location = new Point(8, 0x63);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x71, 12);
            this.label32.TabIndex = 0x17;
            this.label32.Text = "电脑部队防御力乘数";
            this.tbAITroopDefenceRate.Location = new Point(0x84, 0x60);
            this.tbAITroopDefenceRate.Name = "tbAITroopDefenceRate";
            this.tbAITroopDefenceRate.Size = new Size(0x47, 0x15);
            this.tbAITroopDefenceRate.TabIndex = 0x16;
            this.label28.AutoSize = true;
            this.label28.Location = new Point(8, 0x7e);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0x71, 12);
            this.label28.TabIndex = 0x15;
            this.label28.Text = "电脑建筑伤害率乘数";
            this.tbAIArchitectureDamageRate.Location = new Point(0x84, 0x7b);
            this.tbAIArchitectureDamageRate.Name = "tbAIArchitectureDamageRate";
            this.tbAIArchitectureDamageRate.Size = new Size(0x47, 0x15);
            this.tbAIArchitectureDamageRate.TabIndex = 20;
            this.label29.AutoSize = true;
            this.label29.Location = new Point(8, 0x48);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x71, 12);
            this.label29.TabIndex = 0x13;
            this.label29.Text = "电脑部队攻击力乘数";
            this.tbAITroopOffenceRate.Location = new Point(0x84, 0x45);
            this.tbAITroopOffenceRate.Name = "tbAITroopOffenceRate";
            this.tbAITroopOffenceRate.Size = new Size(0x47, 0x15);
            this.tbAITroopOffenceRate.TabIndex = 0x12;
            this.label30.AutoSize = true;
            this.label30.Location = new Point(8, 0x2d);
            this.label30.Name = "label30";
            this.label30.Size = new Size(0x59, 12);
            this.label30.TabIndex = 0x11;
            this.label30.Text = "电脑粮草收入率";
            this.tbAIFoodRate.Location = new Point(0x84, 0x2a);
            this.tbAIFoodRate.Name = "tbAIFoodRate";
            this.tbAIFoodRate.Size = new Size(0x47, 0x15);
            this.tbAIFoodRate.TabIndex = 0x10;
            this.label31.AutoSize = true;
            this.label31.Location = new Point(8, 0x12);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x59, 12);
            this.label31.TabIndex = 15;
            this.label31.Text = "电脑资金收入率";
            this.tbAIFundRate.Location = new Point(0x84, 15);
            this.tbAIFundRate.Name = "tbAIFundRate";
            this.tbAIFundRate.Size = new Size(0x47, 0x15);
            this.tbAIFundRate.TabIndex = 14;
            this.btnOK.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.btnOK.DialogResult = DialogResult.OK;
            this.btnOK.Location = new Point(0x125, 0x1ac);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new Size(0x4b, 0x17);
            this.btnOK.TabIndex = 1;
            this.btnOK.Text = "确定";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new EventHandler(this.btnOK_Click);
            this.btnCancel.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.btnCancel.DialogResult = DialogResult.Cancel;
            this.btnCancel.Location = new Point(0x176, 0x1ac);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new Size(0x4b, 0x17);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.Text = "取消";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.label41.AutoSize = true;
            this.label41.Location = new Point(0x13, 0xf3);
            this.label41.Name = "label41";
            this.label41.Size = new Size(0x71, 12);
            this.label41.TabIndex = 0x15;
            this.label41.Text = "追随将领攻击力加成";
            this.tbFollowedLeaderOffenceRateIncrement.Location = new Point(0x8f, 240);
            this.tbFollowedLeaderOffenceRateIncrement.Name = "tbFollowedLeaderOffenceRateIncrement";
            this.tbFollowedLeaderOffenceRateIncrement.Size = new Size(0x47, 0x15);
            this.tbFollowedLeaderOffenceRateIncrement.TabIndex = 20;
            this.label42.AutoSize = true;
            this.label42.Location = new Point(0x13, 270);
            this.label42.Name = "label42";
            this.label42.Size = new Size(0x71, 12);
            this.label42.TabIndex = 0x17;
            this.label42.Text = "追随将领防御力加成";
            this.tbFollowedLeaderDefenceRateIncrement.Location = new Point(0x8f, 0x10b);
            this.tbFollowedLeaderDefenceRateIncrement.Name = "tbFollowedLeaderDefenceRateIncrement";
            this.tbFollowedLeaderDefenceRateIncrement.Size = new Size(0x47, 0x15);
            this.tbFollowedLeaderDefenceRateIncrement.TabIndex = 0x16;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x1c5, 0x1cb);
            base.Controls.Add(this.btnCancel);
            base.Controls.Add(this.tcOptions);
            base.Controls.Add(this.btnOK);
            base.FormBorderStyle = FormBorderStyle.Fixed3D;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "formOptions";
            base.StartPosition = FormStartPosition.CenterParent;
            this.Text = "游戏设置";
            this.tcOptions.ResumeLayout(false);
            this.tabPageEnvironment.ResumeLayout(false);
            this.tabPageEnvironment.PerformLayout();
            this.tabPagePerson.ResumeLayout(false);
            this.tabPagePerson.PerformLayout();
            this.tabPageParameter.ResumeLayout(false);
            this.tabPageParameter.PerformLayout();
            this.tabPageAIParameter.ResumeLayout(false);
            this.tabPageAIParameter.PerformLayout();
            base.ResumeLayout(false);
        }

        private void LoadCommonDoc()
        {
            this.commonDoc.Load("GameData/GlobalVariables.xml");
            XmlNode nextSibling = this.commonDoc.FirstChild.NextSibling;
            this.cbRunWhileNotFocused.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("RunWhileNotFocused").Value);
            this.cbPlayMusic.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PlayMusic").Value);
            this.cbPlayNormalSound.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PlayNormalSound").Value);
            this.cbPlayBattleSound.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PlayBattleSound").Value);
            this.cbDrawMapVeil.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("DrawMapVeil").Value);
            this.cbDrawTroopAnimation.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("DrawTroopAnimation").Value);
            this.cbSkyEye.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("SkyEye").Value);
            this.cbMultipleResource.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("MultipleResource").Value);
            this.cbSingleSelectionOneClick.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("SingleSelectionOneClick").Value);
            this.cbNoHintOnSmallFacility.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("NoHintOnSmallFacility").Value);
            this.cbHintPopulation.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("HintPopulation").Value);
            this.cbHintPopulationUnder1000.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("HintPopulationUnder1000").Value);
            this.cbPopulationRecruitmentLimit.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PopulationRecruitmentLimit").Value);
            this.cbMilitaryKindSpeedValid.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("MilitaryKindSpeedValid").Value);
            this.tbTroopMoveSpeed.Text = nextSibling.Attributes.GetNamedItem("TroopMoveSpeed").Value;
            this.cbCommonPersonAvailable.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("CommonPersonAvailable").Value);
            this.cbAdditionalPersonAvailable.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("AdditionalPersonAvailable").Value);
            this.cbPlayerPersonAvailable.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PlayerPersonAvailable").Value);
            this.cbPersonNaturalDeath.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("PersonNaturalDeath").Value);
            this.cbIdealTendencyValid.Checked = bool.Parse(nextSibling.Attributes.GetNamedItem("IdealTendencyValid").Value);
        }

        private void LoadParameterDoc()
        {
            this.parameterDoc.Load("GameData/GameParameters.xml");
            XmlNode nextSibling = this.parameterDoc.FirstChild.NextSibling;
            this.tbFindTreasureChance.Text = nextSibling.Attributes.GetNamedItem("FindTreasureChance").Value;
            this.tbLearnSkillDays.Text = nextSibling.Attributes.GetNamedItem("LearnSkillDays").Value;
            this.tbLearnStuntDays.Text = nextSibling.Attributes.GetNamedItem("LearnStuntDays").Value;
            this.tbLearnTitleDays.Text = nextSibling.Attributes.GetNamedItem("LearnTitleDays").Value;
            this.tbFollowedLeaderOffenceRateIncrement.Text = nextSibling.Attributes.GetNamedItem("FollowedLeaderOffenceRateIncrement").Value;
            this.tbFollowedLeaderDefenceRateIncrement.Text = nextSibling.Attributes.GetNamedItem("FollowedLeaderDefenceRateIncrement").Value;
            this.tbInternalRate.Text = nextSibling.Attributes.GetNamedItem("InternalRate").Value;
            this.tbTrainingRate.Text = nextSibling.Attributes.GetNamedItem("TrainingRate").Value;
            this.tbRecruitmentRate.Text = nextSibling.Attributes.GetNamedItem("RecruitmentRate").Value;
            this.tbFundRate.Text = nextSibling.Attributes.GetNamedItem("FundRate").Value;
            this.tbFoodRate.Text = nextSibling.Attributes.GetNamedItem("FoodRate").Value;
            this.tbTroopDamageRate.Text = nextSibling.Attributes.GetNamedItem("TroopDamageRate").Value;
            this.tbArchitectureDamageRate.Text = nextSibling.Attributes.GetNamedItem("ArchitectureDamageRate").Value;
            this.tbDefaultPopulationDevelopingRate.Text = nextSibling.Attributes.GetNamedItem("DefaultPopulationDevelopingRate").Value;
            this.tbSurroundArchitectureDominationUnit.Text = nextSibling.Attributes.GetNamedItem("SurroundArchitectureDominationUnit").Value;
            this.tbFireDamageScale.Text = nextSibling.Attributes.GetNamedItem("FireDamageScale").Value;
            this.tbBuyFoodAgriculture.Text = nextSibling.Attributes.GetNamedItem("BuyFoodAgriculture").Value;
            this.tbSellFoodCommerce.Text = nextSibling.Attributes.GetNamedItem("SellFoodCommerce").Value;
            this.tbFundToFoodMultiple.Text = nextSibling.Attributes.GetNamedItem("FundToFoodMultiple").Value;
            this.tbFoodToFundDivisor.Text = nextSibling.Attributes.GetNamedItem("FoodToFundDivisor").Value;
            this.tbInternalFundCost.Text = nextSibling.Attributes.GetNamedItem("InternalFundCost").Value;
            this.tbRecruitmentFundCost.Text = nextSibling.Attributes.GetNamedItem("RecruitmentFundCost").Value;
            this.tbRecruitmentDomination.Text = nextSibling.Attributes.GetNamedItem("RecruitmentDomination").Value;
            this.tbRecruitmentMorale.Text = nextSibling.Attributes.GetNamedItem("RecruitmentMorale").Value;
            this.tbChangeCapitalCost.Text = nextSibling.Attributes.GetNamedItem("ChangeCapitalCost").Value;
            this.tbHireNoFactionPersonCost.Text = nextSibling.Attributes.GetNamedItem("HireNoFactionPersonCost").Value;
            this.tbConvincePersonCost.Text = nextSibling.Attributes.GetNamedItem("ConvincePersonCost").Value;
            this.tbRewardPersonCost.Text = nextSibling.Attributes.GetNamedItem("RewardPersonCost").Value;
            this.tbSendSpyCost.Text = nextSibling.Attributes.GetNamedItem("SendSpyCost").Value;
            this.tbDestroyArchitectureCost.Text = nextSibling.Attributes.GetNamedItem("DestroyArchitectureCost").Value;
            this.tbInstigateArchitectureCost.Text = nextSibling.Attributes.GetNamedItem("InstigateArchitectureCost").Value;
            this.tbGossipArchitectureCost.Text = nextSibling.Attributes.GetNamedItem("GossipArchitectureCost").Value;
            this.tbClearFieldFundCostUnit.Text = nextSibling.Attributes.GetNamedItem("ClearFieldFundCostUnit").Value;
            this.tbClearFieldAgricultureCostUnit.Text = nextSibling.Attributes.GetNamedItem("ClearFieldAgricultureCostUnit").Value;
            this.tbAIFundRate.Text = nextSibling.Attributes.GetNamedItem("AIFundRate").Value;
            this.tbAIFoodRate.Text = nextSibling.Attributes.GetNamedItem("AIFoodRate").Value;
            this.tbAITroopOffenceRate.Text = nextSibling.Attributes.GetNamedItem("AITroopOffenceRate").Value;
            this.tbAITroopDefenceRate.Text = nextSibling.Attributes.GetNamedItem("AITroopDefenceRate").Value;
            this.tbAIArchitectureDamageRate.Text = nextSibling.Attributes.GetNamedItem("AIArchitectureDamageRate").Value;
            this.tbAITrainingSpeedRate.Text = nextSibling.Attributes.GetNamedItem("AITrainingSpeedRate").Value;
            this.tbAIRecruitmentSpeedRate.Text = nextSibling.Attributes.GetNamedItem("AIRecruitmentSpeedRate").Value;
        }

        private void SaveCommonDoc()
        {
            XmlNode nextSibling = this.commonDoc.FirstChild.NextSibling;
            nextSibling.Attributes.GetNamedItem("RunWhileNotFocused").Value = this.cbRunWhileNotFocused.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PlayMusic").Value = this.cbPlayMusic.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PlayNormalSound").Value = this.cbPlayNormalSound.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PlayBattleSound").Value = this.cbPlayBattleSound.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("DrawMapVeil").Value = this.cbDrawMapVeil.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("DrawTroopAnimation").Value = this.cbDrawTroopAnimation.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("SkyEye").Value = this.cbSkyEye.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("MultipleResource").Value = this.cbMultipleResource.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("SingleSelectionOneClick").Value = this.cbSingleSelectionOneClick.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("NoHintOnSmallFacility").Value = this.cbNoHintOnSmallFacility.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("HintPopulation").Value = this.cbHintPopulation.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("HintPopulationUnder1000").Value = this.cbHintPopulationUnder1000.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PopulationRecruitmentLimit").Value = this.cbPopulationRecruitmentLimit.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("MilitaryKindSpeedValid").Value = this.cbMilitaryKindSpeedValid.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("TroopMoveSpeed").Value = this.tbTroopMoveSpeed.Text;
            nextSibling.Attributes.GetNamedItem("CommonPersonAvailable").Value = this.cbCommonPersonAvailable.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("AdditionalPersonAvailable").Value = this.cbAdditionalPersonAvailable.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PlayerPersonAvailable").Value = this.cbPlayerPersonAvailable.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("PersonNaturalDeath").Value = this.cbPersonNaturalDeath.Checked.ToString();
            nextSibling.Attributes.GetNamedItem("IdealTendencyValid").Value = this.cbIdealTendencyValid.Checked.ToString();
            this.commonDoc.Save("GameData/GlobalVariables.xml");
        }

        private void SaveParameterDoc()
        {
            XmlNode nextSibling = this.parameterDoc.FirstChild.NextSibling;
            nextSibling.Attributes.GetNamedItem("FindTreasureChance").Value = this.tbFindTreasureChance.Text;
            nextSibling.Attributes.GetNamedItem("LearnSkillDays").Value = this.tbLearnSkillDays.Text;
            nextSibling.Attributes.GetNamedItem("LearnStuntDays").Value = this.tbLearnStuntDays.Text;
            nextSibling.Attributes.GetNamedItem("LearnTitleDays").Value = this.tbLearnTitleDays.Text;
            nextSibling.Attributes.GetNamedItem("FollowedLeaderOffenceRateIncrement").Value = this.tbFollowedLeaderOffenceRateIncrement.Text;
            nextSibling.Attributes.GetNamedItem("FollowedLeaderDefenceRateIncrement").Value = this.tbFollowedLeaderDefenceRateIncrement.Text;
            nextSibling.Attributes.GetNamedItem("InternalRate").Value = this.tbInternalRate.Text;
            nextSibling.Attributes.GetNamedItem("TrainingRate").Value = this.tbTrainingRate.Text;
            nextSibling.Attributes.GetNamedItem("RecruitmentRate").Value = this.tbRecruitmentRate.Text;
            nextSibling.Attributes.GetNamedItem("FundRate").Value = this.tbFundRate.Text;
            nextSibling.Attributes.GetNamedItem("FoodRate").Value = this.tbFoodRate.Text;
            nextSibling.Attributes.GetNamedItem("TroopDamageRate").Value = this.tbTroopDamageRate.Text;
            nextSibling.Attributes.GetNamedItem("ArchitectureDamageRate").Value = this.tbArchitectureDamageRate.Text;
            nextSibling.Attributes.GetNamedItem("DefaultPopulationDevelopingRate").Value = this.tbDefaultPopulationDevelopingRate.Text;
            nextSibling.Attributes.GetNamedItem("SurroundArchitectureDominationUnit").Value = this.tbSurroundArchitectureDominationUnit.Text;
            nextSibling.Attributes.GetNamedItem("FireDamageScale").Value = this.tbFireDamageScale.Text;
            nextSibling.Attributes.GetNamedItem("BuyFoodAgriculture").Value = this.tbBuyFoodAgriculture.Text;
            nextSibling.Attributes.GetNamedItem("SellFoodCommerce").Value = this.tbSellFoodCommerce.Text;
            nextSibling.Attributes.GetNamedItem("FundToFoodMultiple").Value = this.tbFundToFoodMultiple.Text;
            nextSibling.Attributes.GetNamedItem("FoodToFundDivisor").Value = this.tbFoodToFundDivisor.Text;
            nextSibling.Attributes.GetNamedItem("InternalFundCost").Value = this.tbInternalFundCost.Text;
            nextSibling.Attributes.GetNamedItem("RecruitmentFundCost").Value = this.tbRecruitmentFundCost.Text;
            nextSibling.Attributes.GetNamedItem("RecruitmentDomination").Value = this.tbRecruitmentDomination.Text;
            nextSibling.Attributes.GetNamedItem("RecruitmentMorale").Value = this.tbRecruitmentMorale.Text;
            nextSibling.Attributes.GetNamedItem("ChangeCapitalCost").Value = this.tbChangeCapitalCost.Text;
            nextSibling.Attributes.GetNamedItem("HireNoFactionPersonCost").Value = this.tbHireNoFactionPersonCost.Text;
            nextSibling.Attributes.GetNamedItem("ConvincePersonCost").Value = this.tbConvincePersonCost.Text;
            nextSibling.Attributes.GetNamedItem("RewardPersonCost").Value = this.tbRewardPersonCost.Text;
            nextSibling.Attributes.GetNamedItem("SendSpyCost").Value = this.tbSendSpyCost.Text;
            nextSibling.Attributes.GetNamedItem("DestroyArchitectureCost").Value = this.tbDestroyArchitectureCost.Text;
            nextSibling.Attributes.GetNamedItem("InstigateArchitectureCost").Value = this.tbInstigateArchitectureCost.Text;
            nextSibling.Attributes.GetNamedItem("GossipArchitectureCost").Value = this.tbGossipArchitectureCost.Text;
            nextSibling.Attributes.GetNamedItem("ClearFieldFundCostUnit").Value = this.tbClearFieldFundCostUnit.Text;
            nextSibling.Attributes.GetNamedItem("ClearFieldAgricultureCostUnit").Value = this.tbClearFieldAgricultureCostUnit.Text;
            nextSibling.Attributes.GetNamedItem("AIFundRate").Value = this.tbAIFundRate.Text;
            nextSibling.Attributes.GetNamedItem("AIFoodRate").Value = this.tbAIFoodRate.Text;
            nextSibling.Attributes.GetNamedItem("AITroopOffenceRate").Value = this.tbAITroopOffenceRate.Text;
            nextSibling.Attributes.GetNamedItem("AITroopDefenceRate").Value = this.tbAITroopDefenceRate.Text;
            nextSibling.Attributes.GetNamedItem("AIArchitectureDamageRate").Value = this.tbAIArchitectureDamageRate.Text;
            nextSibling.Attributes.GetNamedItem("AITrainingSpeedRate").Value = this.tbAITrainingSpeedRate.Text;
            nextSibling.Attributes.GetNamedItem("AIRecruitmentSpeedRate").Value = this.tbAIRecruitmentSpeedRate.Text;
            this.parameterDoc.Save("GameData/GameParameters.xml");
        }
    }

 

}
